
image: Visual Studio 2017

install:
  - ps: Install-Product node 8
  - npm install
  - npm run vendor
  - npm run compile
  - npm run release

build: off

artifacts:
  - path: artifacts/Bakaru-Setup.exe
    name: Bakaru-Setup-win32-x64.exe
